FROM python:3.11-slim
WORKDIR /code
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt
COPY frontend ./frontend
ENV FASTAPI_URL=http://api:8000
CMD ["python", "-m", "frontend.app"]
